version: 1

review:
  enabled: true
  auto_review:
    enabled: true
    trigger: pull_request

  rules:
    - name: "Build check"
      description: "Ensure project builds without errors (mvn clean install)"
      enabled: true

    - name: "Code quality"
      description: "Check for duplicate code, complex methods, missing null checks"
      enabled: true

    - name: "Best practices"
      description: "Suggest using existing enums/constants instead of hardcoded strings"
      enabled: true

  context:
    repository_access: full
    cross_file_analysis: true
