server:
  port: 8088

# Spring
spring:
  application:
    name: email-service

  # Redis Configuration
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  # Kafka Configuration
  kafka:
    bootstrap-servers:
      - ${KAFKA_BROKER_URL:localhost:9092}
    consumer:
      group-id: email-service-consumer-group
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email}
    password: ${MAIL_PASSWORD:your_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:eureka123@localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      version: 1.0.0
      environment: ${spring.profiles.active}

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/email-service.log

# gRPC Configuration
grpc:
  client:
    user-service:
      address: ${USER-SERVICE-GRPC:0.0.0.0}
      port: 9091
    checklist-service:
      address: ${CHECKLIST-SERVICE-GRPC:0.0.0.0}
      port: 9093

springdoc:
  api-docs:
    path: /email-service/v3/api-docs
  swagger-ui:
    path: /email-service/swagger/index.html

# Custom properties:
custom:
  client:
    address: ${CUSTOM_CLIENT_ADDRESS:http://localhost:5173}