server:
  port: 8089

# Spring
spring:
  application:
    name: file-service

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  servlet:
    multipart:
          max-file-size: 10MB
          max-request-size: 10MB
          enabled: true

# AWS S3 Configuration
cloud:
  aws:
    region: ap-southeast-1
    s3:
      bucket-name:"${AWS_S3_BUCKET_NAME:file-service-bucket}"
    credentials:
      access-key: "${AWS_ACCESS_KEY_ID:your_access_key}"
      secret-key: "${AWS_SECRET_ACCESS_KEY:your_secret_key}"


# OpenAPI Configuration
springdoc:
  api-docs:
    path: /file-service/v3/api-docs
  swagger-ui:
    path: /file-service/swagger/index.html

