spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/odc_dev
    username: odc_user
    password: odc_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

logging:
  level:
    root: INFO
    com.odc: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT configuration
jwt:
  secret: dev-secret-key-for-jwt-token-signing
  expiration: 86400000  # 24 hours