server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    root: INFO
    com.odc: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG