spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/config-repo
          clone-on-start: true
          force-pull: true
          default-label: main
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    root: INFO
    com.odc: DEBUG
    org.springframework.cloud.config: DEBUG

