server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file://${user.dir}/config-repo}
          clone-on-start: true
          force-pull: true
        health:
          repositories:
            config-repo:
              label: main
              name: config-repo
              profiles: dev,prod

  # Security
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config-user}
      password: ${CONFIG_SERVER_PASSWORD:config-password}
      roles: ADMIN

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      version: 1.0.0
      environment: ${spring.profiles.active}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,env,configprops
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/config-server.log