defaults:
  channels: [ WEB ]          # Nếu không có channel nào được set
  target_strategy: ROLE    # Default lấy theo role
  roles: [ "ADMIN" ]         # Default gửi cho admin

rules:
  COMPANY_REGISTRATION:
    channels: [ WEB ]
    target_strategy: ROLE
    roles: [ "LAB_ ADMIN", "SUPER_ADMIN" ]

  TASK_ASSIGNED:
    channels: [ MOBILE, WEB ]
    target_strategy: USER

  SYSTEM_ALERT:
    channels: [ WEB, MOBILE ]
    target_strategy: ALL

  USER_MENTIONED:
    channels: [ WEB ]
    target_strategy: USER

  PERFORMANCE_REVIEW:
    channels: [ MOBILE ]
    target_strategy: USER
